### PR TITLE
Adding support for ntohing Phone 1

### PR DESCRIPTION
**Pull request by index986**
### Checklist

* [x] Is what you changed Tested?
* [ ] Are the Patched Files Compiled?
* [x] Did you Clean Up the Files?

### CODE REVIEW

**Review by Robotix22 — CHANGES_REQUESTED** [review]
Remove the `a` & `b` File in the `FeatureEnablerDxe` Folder
And Create a `README.md` File to Tell why and What was Patched

**Comment by index986** [comment]
Btw done

**Comment by Robotix22** [comment]
No, You're Not.
You didn't Remove the `a` & `b` File.
Also Clean Up the Binaries, And spacewar really has EBL App?

**Comment by index986** [comment]
Wait what

**Comment by index986** [comment]
Strange. I remember that i removed it. Okay anyway i will do it rn

**Comment by index986** [comment]
Im not really sure what is ebl app. But i cleaned everything. ( Will push it in a second )

**Comment by Robotix22** [comment]
EBL is an early Version of UEFI Shell
And it is Located in `EmbeddedPkg`

**Comment by index986** [comment]
Maybe it do. Should be removed?

**Comment by Robotix22** [comment]
If it isn't in your XBL, Then yes

**Comment by index986** [comment]
I cant really check but iirc yes ( i didnt touch ```EmbeddedPkg``` folder)

**Comment by Robotix22** [comment]
Then just Keep it, And Please Clean up your Binaries

**Comment by index986** [comment]
They are cleaned up. Inf's looks exactly same as pong's or other device

**Comment by Robotix22** [comment]
I still see `UEFI Reader` Header in most .inf Files

**Review by Robotix22 — APPROVED** [review]

**Pull request merged**
