### PR TITLE
Update bins to A15 Beta 1

### PR DESCRIPTION
**Pull request by index986**
### What Changed

updated bins of pong
### Reason

idk
### Checklist

* [x] Is what you changed Tested?
* [ ] Are the Patched Files Compiled?
* [x] Did you Clean Up the Files? ( at least should be cleaned up )

### CODE REVIEW

**Comment by Robotix22** [comment]
Please Run `CleanUp.sh` once.

**Comment by index986** [comment]
For some reason it says clean up finished when half of files are still uncleaned

**Comment by Robotix22** [comment]
Are you Moving the File by any Chance?
It needs to be Executes at the Location where it is already.
Like, Run this while you are in the `Device-Binares` Folder:
```bash
./CleanUp.sh
```

**Comment by index986** [comment]
Nope not moving it

**Comment by Robotix22** [comment]
Yes, And Remove the Compiler Notes after it.

**Review by Robotix22 — APPROVED** [review]

**Pull request merged**
