### PR TITLE
Adding Mi 8 Pro binaries

### PR DESCRIPTION
**Pull request by index986**
### Reason

Adding Mi 8 Pro binaries
### Checklist

* [x] Is what you changed Tested?
* [ ] Are the Patched Files Compiled?
* [x] Did you Clean Up the Files?

### CODE REVIEW

**Comment by Robotix22** [comment]
Are the Patched Files really Compiled by you?

**Comment by index986** [comment]
No. I have no idea what ppl from renegade did to make QcomChargerLaDxe work so i copied it. Lemme fix it

**Comment by Daniel224455** [comment]
^ ебануты лох LOL

**Review by Robotix22 — CHANGES_REQUESTED** [review]
Don't use Reneagde Drivers please
These Drivers are Compiled from Source

**Comment by index986** [comment]
Done

**Review by Robotix22 — APPROVED** [review]

**Pull request merged**
