### PR TITLE
sapphire: Add binaries

### PR DESCRIPTION
**Pull request by hiprivsid**
### What Changed

Added binaries for Xiaomi Redmi Note 13 4G (sapphire/sapphiren)

### Reason

I am porting UEFI to sapphire

### Checklist

* [ ] Is what you changed Tested? 
* [x] Are the Patched Files Compiled?
* [ ] Did you Clean Up the Files?

### CODE REVIEW

**Comment by index986** [comment]
You should clean files

**Comment by index986** [comment]
Run ./CleanUp.sh in Binaries folder

**Comment by Daniel224455** [comment]
he left the uefireader stuff in inf files lmao

**Comment by hiprivsid** [comment]
> You should clean files

oh, ok

**Pull request closed without merging**
