### PR TITLE
Adding UsbMsdDxe patch

### PR DESCRIPTION
**Pull request by index986**
### Checklist

* [s] Is what you changed Tested?
* [ ]Are the Patched Files Compiled?
* [x] Did you Clean Up the Files?

### CODE REVIEW

**Comment by Robotix22** [comment]
Is it Compiled tho?

**Comment by index986** [comment]
I patched it

**Comment by Robotix22** [comment]
Why is it then Parked as Compiled by you?

**Comment by index986** [comment]
Actually idk

**Review by Robotix22 — APPROVED** [review]

**Pull request merged**
