### PR TITLE
Vayu: Replace compiled DisplayDxe with patched one

### PR DESCRIPTION
**Pull request by remtrik**
### What Changed

Yes we patched stock DisplayDxe after 1 year

### Reason

I forgot to to it before

### Checklist

* [x] Is what you changed Tested?
* [ ] Are the Patched Files Compiled?
* [x] Did you Clean Up the Files?

### CODE REVIEW

**Review by Robotix22 — COMMENTED** [review]
Does this work with the Touch Driver in Windows?

**Comment by remtrik** [comment]
> Does this work with the Touch Driver in Windows?

Yes, PanelId in panel xmls were added so that gpu driver passes curent panel used to touch driver

**Comment by N1kroks** [comment]
Filename in inf is changed, but EFI filename did not changed

**Comment by Robotix22** [comment]
Nice, I patched it before and Touch Driver didn't work

**Comment by remtrik** [comment]
> Filename in inf is changed, but EFI filename did not changed

Where exactly

**Comment by N1kroks** [comment]
oh nvm im blind

**Comment by Robotix22** [comment]
Seems, Fine then

**Pull request merged**
